name: camo-banano-light-wallet
summary: camo-banano-light-wallet
description: |
      camo-banano-light-wallet
version: test
grade: stable
confinement: strict
base: core22

apps:
  camo-banano-light-wallet:
    command: npm start
    plugs: []

parts:
  camo-banano-light-wallet:
    plugin: nil