name: camo-banano-light-wallet
version: git
confinement: strict
base: core22

apps:
  camo-banano-light-wallet:
    command: bin/camo-banano-light-wallet

parts:
  camo-banano-light-wallet:
    plugin: npm
    npm-node-version: v18.13.0
    source: .